### ISSUE TITLE
Why using Client of python version needs to install tensorflow? 

### ISSUE THREAD

**Issue by huyangc** [huawei-clouds/dls-tfserving-client#1]
I don't think it is necessary to use tensorflow in client?

**Comment by gclouding** [comment]
@huyangc Tensorflow serving defines its own internal data structure such as tensorproto, so the request data, such as images, text, should be convert to the data structures defined by tensorflow serving. The conversion requires calling some tensorflow APIs. So tensorflow should be installed in advance.

**Comment by huyangc** [comment]
It means that you use the server service provided by tensorflow other than writing an socket like server(http or smth else) just to receive the input and return the output.

**Comment by gclouding** [comment]
@huyangc Right. The client provided here should be used together with tensorflow serving provided by tensorflow community. The communication is based on grpc protocol.

**Comment by huyangc** [comment]
Thanks for detail explanation
